version: 2
jobs:
  build:
    working_directory: /app/homebrew-monitor-auth
    docker:
      - image: node:6.2.0
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Install Docker
          command: |
            set -x
            VER="17.04.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: 
          name: Build Test Image
          command: docker build -t codemeister/homebrew-monitor-auth -f ./Dockerfile.test .
      - run:
          name: Run Test Image
          command: docker run -it codemeister/homebrew-monitor-auth
      